name: Build

on:
  push:
    branches:
        - '**'

jobs:
  cross-build:
    name: 'Cross build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          # 'alpha-unknown-linux-gnu',
          'x86_64-unknown-linux-gnu',
          'i386-unknown-linux-gnu',
          # 'arm-unknown-linux-gnueabi',
          'arm-unknown-linux-gnueabihf',
          # 'hppa-unknown-linux-gnu',
          'aarch64-unknown-linux-gnu',
          # 'mips-unknown-linux-gnu',
          # 'mipsel-unknown-linux-gnu',
          'powerpc-unknown-linux-gnu',
          # 's390-unknown-linux-gnu',
          's390x-unknown-linux-gnu',
          'sparc-unknown-linux-gnu',
          'powerpc64le-unknown-linux-gnu'
        ]
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Install Clang 20
      run: |
        wget 'https://apt.llvm.org/llvm.sh'
        sudo bash './llvm.sh' '20'
        
        for old in '/usr/bin/'*'-20'; do
            declare new="$(sed 's/-20//g' <<< "${old}")"
            sudo unlink "${new}" 2>/dev/null || true
            sudo ln --symbolic "${old}" "${new}"
        done
    - name: Build LLVM LLD with OBGGCC
      run: |
        source './submodules/obggcc/tools/setup_toolchain.sh'
        bash './build.sh' '${{ matrix.target }}'
    - name: Generate tarball
      run: |
        declare tarball_filename='/tmp/${{ matrix.target }}.tar.xz'
        tar --directory='/tmp' --create --file=- 'llvm-ld' | xz --threads='0' --compress -9 > "${tarball_filename}"
        sha256sum "${tarball_filename}" | sed 's|/tmp/||' > "${tarball_filename}.sha256"
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.target }}
        if-no-files-found: error
        path: |
          /tmp/${{ matrix.target }}.tar.xz
          /tmp/${{ matrix.target }}.tar.xz.sha256
